// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV3zZJU5eJwFM9gtNdv3avobIsz-E3tV0',
    appId: '1:986826652356:web:285cd0a2bbed67ef1de791',
    messagingSenderId: '986826652356',
    projectId: 'smart-learning-app-43982',
    authDomain: 'smart-learning-app-43982.firebaseapp.com',
    storageBucket: 'smart-learning-app-43982.firebasestorage.app',
    measurementId: 'G-0CSTNRQ3JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIAY-z6e3uTUB9_9KITjPZQpOznOALqJo',
    appId: '1:986826652356:android:128be790c555e12f1de791',
    messagingSenderId: '986826652356',
    projectId: 'smart-learning-app-43982',
    storageBucket: 'smart-learning-app-43982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR7m-4hRmGsDbkV00QxtTw5jEppENyFOs',
    appId: '1:986826652356:ios:072b3f658532dbaf1de791',
    messagingSenderId: '986826652356',
    projectId: 'smart-learning-app-43982',
    storageBucket: 'smart-learning-app-43982.firebasestorage.app',
    iosClientId: '986826652356-gdmscof92bp0co2q5ku5294mb9kh7prr.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR7m-4hRmGsDbkV00QxtTw5jEppENyFOs',
    appId: '1:986826652356:ios:072b3f658532dbaf1de791',
    messagingSenderId: '986826652356',
    projectId: 'smart-learning-app-43982',
    storageBucket: 'smart-learning-app-43982.firebasestorage.app',
    iosClientId: '986826652356-gdmscof92bp0co2q5ku5294mb9kh7prr.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV3zZJU5eJwFM9gtNdv3avobIsz-E3tV0',
    appId: '1:986826652356:web:ae9416b00d33bf181de791',
    messagingSenderId: '986826652356',
    projectId: 'smart-learning-app-43982',
    authDomain: 'smart-learning-app-43982.firebaseapp.com',
    storageBucket: 'smart-learning-app-43982.firebasestorage.app',
    measurementId: 'G-6RNPEP9F47',
  );
}
